import org.apache.spark.sql.SparkSession

/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
class Library {
  def someLibraryMethod(): Boolean = true

  def dummy: Unit = {
    val spark = SparkSession.builder()
      .appName("dummy")
  }
}
