/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.oclc.hadoop.perf.java;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
